# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_trainer.ui',
# licensing of 'create_trainer.ui' applies.
#
# Created: Sun May 24 13:06:24 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(573, 669)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(0, 0, 141, 20))
        self.name.setObjectName("name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 61, 21))
        self.label_4.setObjectName("label_4")
        self.pokemon1_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_combo.setGeometry(QtCore.QRect(60, 90, 61, 22))
        self.pokemon1_combo.setObjectName("pokemon1_combo")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 90, 61, 21))
        self.label_5.setObjectName("label_5")
        self.pokemon2_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_combo.setGeometry(QtCore.QRect(240, 90, 61, 22))
        self.pokemon2_combo.setObjectName("pokemon2_combo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 120, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 120, 61, 21))
        self.label_7.setObjectName("label_7")
        self.pokemon1_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_move1.setGeometry(QtCore.QRect(0, 140, 71, 22))
        self.pokemon1_move1.setObjectName("pokemon1_move1")
        self.pokemon1_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_move2.setGeometry(QtCore.QRect(100, 140, 71, 22))
        self.pokemon1_move2.setObjectName("pokemon1_move2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 170, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 170, 61, 21))
        self.label_9.setObjectName("label_9")
        self.pokemon1_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_move3.setGeometry(QtCore.QRect(0, 190, 71, 22))
        self.pokemon1_move3.setObjectName("pokemon1_move3")
        self.pokemon1_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_move4.setGeometry(QtCore.QRect(100, 190, 71, 22))
        self.pokemon1_move4.setObjectName("pokemon1_move4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 120, 61, 21))
        self.label_10.setObjectName("label_10")
        self.pokemon2_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_move1.setGeometry(QtCore.QRect(210, 140, 71, 22))
        self.pokemon2_move1.setObjectName("pokemon2_move1")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(320, 120, 61, 21))
        self.label_11.setObjectName("label_11")
        self.pokemon2_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_move2.setGeometry(QtCore.QRect(320, 140, 71, 22))
        self.pokemon2_move2.setObjectName("pokemon2_move2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 220, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(0, 250, 61, 21))
        self.label_13.setObjectName("label_13")
        self.pokemon1_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon1_item.setGeometry(QtCore.QRect(40, 250, 131, 22))
        self.pokemon1_item.setObjectName("pokemon1_item")
        self.pokemon2_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_move3.setGeometry(QtCore.QRect(210, 190, 71, 22))
        self.pokemon2_move3.setObjectName("pokemon2_move3")
        self.pokemon2_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_move4.setGeometry(QtCore.QRect(320, 190, 71, 22))
        self.pokemon2_move4.setObjectName("pokemon2_move4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(210, 170, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(320, 170, 61, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(200, 220, 31, 21))
        self.label_16.setObjectName("label_16")
        self.pokemon1_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon1_level.setGeometry(QtCore.QRect(40, 220, 131, 22))
        self.pokemon1_level.setObjectName("pokemon1_level")
        self.pokemon2_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon2_level.setGeometry(QtCore.QRect(240, 220, 111, 22))
        self.pokemon2_level.setObjectName("pokemon2_level")
        self.pokemon2_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon2_item.setGeometry(QtCore.QRect(240, 250, 111, 22))
        self.pokemon2_item.setObjectName("pokemon2_item")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(200, 250, 61, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(410, 90, 61, 21))
        self.label_18.setObjectName("label_18")
        self.pokemon3_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_combo.setGeometry(QtCore.QRect(470, 90, 71, 22))
        self.pokemon3_combo.setObjectName("pokemon3_combo")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(0, 360, 61, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(0, 380, 61, 21))
        self.label_22.setObjectName("label_22")
        self.pokemon4_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_combo.setGeometry(QtCore.QRect(60, 360, 61, 22))
        self.pokemon4_combo.setObjectName("pokemon4_combo")
        self.pokemon4_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_move1.setGeometry(QtCore.QRect(0, 400, 71, 22))
        self.pokemon4_move1.setObjectName("pokemon4_move1")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(100, 380, 61, 21))
        self.label_23.setObjectName("label_23")
        self.pokemon4_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_move2.setGeometry(QtCore.QRect(100, 400, 71, 22))
        self.pokemon4_move2.setObjectName("pokemon4_move2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(0, 430, 61, 21))
        self.label_24.setObjectName("label_24")
        self.pokemon4_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_move3.setGeometry(QtCore.QRect(0, 450, 71, 22))
        self.pokemon4_move3.setObjectName("pokemon4_move3")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(100, 430, 61, 21))
        self.label_25.setObjectName("label_25")
        self.pokemon4_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_move4.setGeometry(QtCore.QRect(100, 450, 71, 22))
        self.pokemon4_move4.setObjectName("pokemon4_move4")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(0, 480, 61, 21))
        self.label_19.setObjectName("label_19")
        self.pokemon4_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon4_level.setGeometry(QtCore.QRect(30, 480, 111, 22))
        self.pokemon4_level.setObjectName("pokemon4_level")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(0, 500, 61, 21))
        self.label_20.setObjectName("label_20")
        self.pokemon4_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon4_item.setGeometry(QtCore.QRect(30, 500, 111, 22))
        self.pokemon4_item.setObjectName("pokemon4_item")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(140, 0, 111, 21))
        self.save.setObjectName("save")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(200, 350, 61, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(200, 380, 61, 21))
        self.label_27.setObjectName("label_27")
        self.pokemon5_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_move1.setGeometry(QtCore.QRect(200, 400, 71, 22))
        self.pokemon5_move1.setObjectName("pokemon5_move1")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(200, 430, 61, 21))
        self.label_28.setObjectName("label_28")
        self.pokemon5_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_move3.setGeometry(QtCore.QRect(200, 450, 71, 22))
        self.pokemon5_move3.setObjectName("pokemon5_move3")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(300, 380, 61, 21))
        self.label_29.setObjectName("label_29")
        self.pokemon5_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_move2.setGeometry(QtCore.QRect(290, 400, 71, 22))
        self.pokemon5_move2.setObjectName("pokemon5_move2")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(290, 430, 61, 21))
        self.label_30.setObjectName("label_30")
        self.pokemon5_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_move4.setGeometry(QtCore.QRect(290, 450, 71, 22))
        self.pokemon5_move4.setObjectName("pokemon5_move4")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(200, 480, 61, 21))
        self.label_31.setObjectName("label_31")
        self.pokemon5_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon5_level.setGeometry(QtCore.QRect(230, 480, 111, 22))
        self.pokemon5_level.setObjectName("pokemon5_level")
        self.pokemon5_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_item.setGeometry(QtCore.QRect(230, 500, 111, 22))
        self.pokemon5_item.setObjectName("pokemon5_item")
        self.pokemon5_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon5_combo.setGeometry(QtCore.QRect(260, 350, 61, 22))
        self.pokemon5_combo.setObjectName("pokemon5_combo")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(410, 120, 61, 21))
        self.label_32.setObjectName("label_32")
        self.pokemon3_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_move1.setGeometry(QtCore.QRect(410, 140, 71, 22))
        self.pokemon3_move1.setObjectName("pokemon3_move1")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(510, 120, 61, 21))
        self.label_33.setObjectName("label_33")
        self.pokemon3_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_move2.setGeometry(QtCore.QRect(500, 140, 71, 22))
        self.pokemon3_move2.setObjectName("pokemon3_move2")
        self.pokemon3_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_move3.setGeometry(QtCore.QRect(410, 190, 71, 22))
        self.pokemon3_move3.setObjectName("pokemon3_move3")
        self.pokemon3_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_move4.setGeometry(QtCore.QRect(500, 190, 71, 22))
        self.pokemon3_move4.setObjectName("pokemon3_move4")
        self.pokemon3_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon3_level.setGeometry(QtCore.QRect(450, 220, 121, 22))
        self.pokemon3_level.setObjectName("pokemon3_level")
        self.pokemon3_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon3_item.setGeometry(QtCore.QRect(450, 250, 121, 22))
        self.pokemon3_item.setObjectName("pokemon3_item")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(410, 220, 31, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(410, 250, 61, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(410, 350, 61, 21))
        self.label_36.setObjectName("label_36")
        self.pokemon6_combo = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_combo.setGeometry(QtCore.QRect(470, 350, 71, 22))
        self.pokemon6_combo.setObjectName("pokemon6_combo")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(410, 380, 61, 21))
        self.label_37.setObjectName("label_37")
        self.pokemon6_move1 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_move1.setGeometry(QtCore.QRect(410, 400, 71, 22))
        self.pokemon6_move1.setObjectName("pokemon6_move1")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(510, 380, 61, 21))
        self.label_38.setObjectName("label_38")
        self.pokemon6_move2 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_move2.setGeometry(QtCore.QRect(500, 400, 71, 22))
        self.pokemon6_move2.setObjectName("pokemon6_move2")
        self.pokemon6_move3 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_move3.setGeometry(QtCore.QRect(410, 450, 71, 22))
        self.pokemon6_move3.setObjectName("pokemon6_move3")
        self.pokemon6_move4 = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_move4.setGeometry(QtCore.QRect(500, 450, 71, 22))
        self.pokemon6_move4.setObjectName("pokemon6_move4")
        self.pokemon6_level = QtWidgets.QSpinBox(self.centralwidget)
        self.pokemon6_level.setGeometry(QtCore.QRect(460, 480, 111, 22))
        self.pokemon6_level.setObjectName("pokemon6_level")
        self.pokemon6_item = QtWidgets.QComboBox(self.centralwidget)
        self.pokemon6_item.setGeometry(QtCore.QRect(460, 500, 111, 22))
        self.pokemon6_item.setObjectName("pokemon6_item")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(200, 500, 61, 21))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(430, 500, 61, 21))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(430, 480, 31, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(410, 170, 61, 21))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(510, 170, 61, 21))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(410, 430, 61, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(500, 430, 61, 21))
        self.label_45.setObjectName("label_45")
        self.pokemon1_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon1_image.setGeometry(QtCore.QRect(60, 20, 71, 71))
        self.pokemon1_image.setText("")
        self.pokemon1_image.setObjectName("pokemon1_image")
        self.pokemon2_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon2_image.setGeometry(QtCore.QRect(240, 20, 71, 71))
        self.pokemon2_image.setText("")
        self.pokemon2_image.setObjectName("pokemon2_image")
        self.pokemon3_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon3_image.setGeometry(QtCore.QRect(470, 20, 81, 71))
        self.pokemon3_image.setText("")
        self.pokemon3_image.setObjectName("pokemon3_image")
        self.pokemon4_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon4_image.setGeometry(QtCore.QRect(60, 280, 81, 71))
        self.pokemon4_image.setText("")
        self.pokemon4_image.setObjectName("pokemon4_image")
        self.pokemon5_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon5_image.setGeometry(QtCore.QRect(260, 280, 81, 71))
        self.pokemon5_image.setText("")
        self.pokemon5_image.setObjectName("pokemon5_image")
        self.pokemon6_image = QtWidgets.QLabel(self.centralwidget)
        self.pokemon6_image.setGeometry(QtCore.QRect(470, 280, 81, 71))
        self.pokemon6_image.setText("")
        self.pokemon6_image.setObjectName("pokemon6_image")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 30))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "Trainer Creator", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 1", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 2", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("mainWindow", "Level:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("mainWindow", "Level:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 3", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 4", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("mainWindow", "Level:", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.save.setText(QtWidgets.QApplication.translate("mainWindow", "Save", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 5", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("mainWindow", "Level:", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("mainWindow", "Level:", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("mainWindow", "Pokemon 6", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("mainWindow", "Move 1", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("mainWindow", "Move 2", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("mainWindow", "Item", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("mainWindow", "Level", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("mainWindow", "Move 3", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("mainWindow", "Move 4", None, -1))

